### ISSUE TITLE
Incorrect spans generated for comma-separated selectors

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/srclib-css#6]
Seen on https://github.com/chris-ramon/testrepo

There are two defs

```json
    {
      "UnitType": "basic-css",
      "Unit": "testrepo",
      "Path": "main.css.btn:active:focus",
      "Name": ".btn:active:focus",
      "File": "main.css",
      "DefStart": 770,
      "DefEnd": 787,
      "Data": {
        "Name": "",
        "Keyword": "selector",
        "Type": "",
        "Kind": "class",
        "Separator": ""
      }
    },
```

and 

```json
    {
      "UnitType": "basic-css",
      "Unit": "testrepo",
      "Path": "main.css.btn:focus",
      "Name": ".btn:focus",
      "File": "main.css",
      "DefStart": 769,
      "DefEnd": 779,
      "Data": {
        "Name": "",
        "Keyword": "selector",
        "Type": "",
        "Kind": "class",
        "Separator": ""
      }
    },
```

they both match the following CSS rule

```css
.btn:focus,
.btn:active:focus,
.btn.active:focus,
.btn.focus,
.btn:active.focus,
.btn.active.focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
```

There are the following issues:
- def spans are intersected [769, 779), [770, 787) (should not)
- spans calculated incorrectly [769, 779) is `.btn:focus` and [770, 787) is `btn:focus,\n.btn:a` (should be `.btn:focus` and `.btn.active:focus`
